/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and kept in source so TypeScript
// understands Next-specific imports before the first local build.
